#
# Play:: Laptop
#
# Copyright 2024 Andrew Jones
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

  - name: Laptop
    hosts: all
    tasks:
      - name: Install laptop-related packages
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - acpi
            - fancontrol
            - firmware-linux-nonfree
            - iw
            - lshw
            - network-manager
            - nscd
            - wireless-tools # iwconfig
      - name: Install non-free firmware
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - firmware-linux-nonfree
        register: firmware_linux_nonfree

      - name: Collect network info
        shell: "/bin/lshw -c network"
        ignore_errors: true
        register: lshw_network

      - name: Disable wifi power management in NM
        ansible.builtin.template:
          src: templates/NetworkManager/wifi_power_management.conf.j2
          dest: /etc/NetworkManager/conf.d/wifi_power_management.conf
          owner: root
          group: root
          mode: 0444
        register: wifi_power_management

      - name: Install script to disable wifi power management for ath11k
        ansible.builtin.template:
          src: templates/ath11k/ath11k_disable_power_management.sh
          dest: /sbin/ath11k_disable_power_management.sh
          owner: root
          group: root
          mode: 0544
        when: lshw_network.stdout.find('QCNFA') > -1

      - name: Disable wifi power management on module load for ath11k_pci
        ansible.builtin.template:
          src: templates/ath11k/ath11k_pci.rules
          dest: /etc/udev/rules.d/83-ath11k_pci.rules
          owner: root
          group: root
          mode: 0444
        when: lshw_network.stdout.find('QCNFA') > -1
        
      - name: Disable ath11k_pci during suspend/resume
        ansible.builtin.template:
          src: templates/ath11k/ath11k_sleep.sh
          dest: /lib/systemd/system-sleep/ath11k_sleep
          owner: root
          group: root
          mode: 0544
        when: lshw_network.stdout.find('QCNFA') > -1
          
      - name: Restart N-M
        ansible.builtin.service:
          name: NetworkManager
          state: restarted
        when: wifi_power_management.changed

      # TODO: reload affected wireless modules when firmware changes
