#
# Play:: X11
#
# Copyright 2022 Andrew Jones
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

  - import_playbook: fonts.yml

  - name: X11
    hosts: all
    tasks:
      - name: Install Xorg
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - lshw
            - mesa-utils
            - xserver-xorg
            # This is still way better than libinput in 2022
            - xserver-xorg-input-all
            - xserver-xorg-video-all
            
      - name: Collect graphics info
        shell: "/bin/lshw -c display"
        ignore_errors: true
        register: lshw_graphics
        
      - name: Configure X11 Synaptics driver
        ansible.builtin.template:
          src: templates/xorg.conf.d/20-synaptics.conf.j2
          dest: /etc/X11/xorg.conf.d/20-synaptics.conf
          owner: root
          group: root
          mode: 0444
          
      - name: Configure Intel graphics
        ansible.builtin.template:
          src: templates/xorg.conf.d/20-intel.conf.j2
          dest: /etc/X11/xorg.conf.d/20-intel.conf
          owner: root
          group: root
          mode: 0444
        when: lshw_graphics.stdout.find('Intel') != -1
        
      - name: Configure AMD graphics
        ansible.builtin.template:
          src: templates/xorg.conf.d/20-amdgpu.conf.j2
          dest: /etc/X11/xorg.conf.d/20-amdgpu.conf
          owner: root
          group: root
          mode: 0444
        when: lshw_graphics.stdout.find('AMD') != -1

      - name: Preseed x-display-manager
        debconf:
          name: xdm
          question: shared/default-x-display-manager
          vtype: string
          value: xdm

      - name: Install xdm
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - xdm
            
      - name: Start xdm
        ansible.builtin.service:
          name: xdm
          state: started
