#
# Play:: Authenticator
#
# Copyright 2023 Andrew Jones
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


  - name: Authenticator
    hosts: all
    vars:
      - yubico_path: '/opt/yubico'
      - yubico_developer_fingerprints:
          - 20EE325B86A81BCBD3E56798F04367096FBA95E8

    tasks:
      - name: Install requisite packages
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 300
          state: latest
          name:
            - gpg
            - tar
            - gzip
        
      - name: Install Yubico developers GPG keys
        ansible.builtin.shell: 'gpg --list-keys {{item}} || gpg --recv-keys {{item}}'
        loop: '{{yubico_developer_fingerprints}}'

      - name: Create target directories
        ansible.builtin.file:
          path: '{{yubico_path}}/{{item}}'
          state: directory
          mode: 0555
        with_items:
          - '.'
          - 'downloads'
          - 'authenticator'

      - name: Download Yubico authenticator
        ansible.builtin.get_url:
          url: 'https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz'
          dest: '{{yubico_path}}/downloads/yubico-authenticator-latest-linux.tar.gz'
          mode: '0444'

      - name: Download Yubico authenticator signature
        ansible.builtin.get_url:
          url: 'https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz.sig'
          dest: '{{yubico_path}}/downloads/yubico-authenticator-latest-linux.tar.gz.sig'
          mode: '0444'

      - name: Verify archive
        ansible.builtin.shell: 'gpg --verify {{yubico_path}}/downloads/yubico-authenticator-latest-linux.tar.gz.sig'

      - name: Extract archive
        ansible.builtin.unarchive:
          src: '{{yubico_path}}/downloads/yubico-authenticator-latest-linux.tar.gz'
          dest: '{{yubico_path}}/authenticator'
          extra_opts: [--strip-components=1]

      - name: Create a symlink
        ansible.builtin.file:
          src: '{{yubico_path}}/authenticator/authenticator'
          dest: '/usr/bin/yubico_authenticator'
          mode: 0555
          state: link
